[package]
name = "rtrace_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rtrace_core = { path = "../rtrace_core" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
colored = "2.1"
